[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  command = "npm run build"
  publish = "build" # Beispiel: Hier wird das Verzeichnis "build" als Veröffentlichungsverzeichnis festgelegt

