[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "netlify-plugin-cypress"
pinned_version = "2.2.0" # Beispiel: Die angeheftete Version des Plugins

[plugins.inputs]
# Hier können optionale Eingaben für das Plugin angegeben werden
